import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck, Users, GraduationCap, BookOpen, DoorOpen, AlertTriangle, BrainCircuit } from 'lucide-react';
import Layout from './components/Layout';
import StatCard from './components/StatCard';
import CrudPage from './components/CrudPage';
import { listenCollection, collections, createItem } from './services/firestoreCrud';
import { DAYS, PAIRS, lessonTypeLabel, lessonTypeStyle, findBy, teacherHours, detectConflicts, optimizeSuggestion } from './utils/scheduler';
import React from "react";

const empty={faculties:[],departments:[],groups:[],teachers:[],subjects:[],rooms:[],buildings:[],lessons:[],workloads:[]};
function opts(rows,label='name'){return rows.map(x=>({value:x.id,label:x[label]||x.name||x.title||x.id}))}
function lookup(rows,label='name'){return Object.fromEntries(rows.map(x=>[x.id,x[label]||x.name||x.title||x.id]))}

export default function App(){
 const [page,setPage]=useState('dashboard'); const [data,setData]=useState(empty);
 useEffect(()=>{const unsubs=Object.keys(empty).map(k=>listenCollection(collections[k],rows=>setData(d=>({...d,[k]:rows})))); return ()=>unsubs.forEach(u=>u&&u());},[]);
 const conflicts=useMemo(()=>detectConflicts(data.lessons),[data.lessons]);
 const score=useMemo(()=>optimizeSuggestion({teachers:data.teachers,lessons:data.lessons}),[data.teachers,data.lessons]);
 const lookups={facultyId:lookup(data.faculties),departmentId:lookup(data.departments),buildingId:lookup(data.buildings),groupId:lookup(data.groups),teacherId:lookup(data.teachers),subjectId:lookup(data.subjects),roomId:lookup(data.rooms,'number')};
 return <Layout page={page} setPage={setPage} conflictCount={conflicts.length}>
  {page==='dashboard'&&<Dashboard data={data} conflicts={conflicts} score={score}/>} 
  {page==='schedule'&&<Schedule data={data} lookups={lookups}/>} 
  {page==='workloads'&&<Workloads data={data}/>} 
  {page==='conflicts'&&<Conflicts conflicts={conflicts} data={data}/>} 
  {page==='faculties'&&<CrudPage title="Fakultet" collectionName="faculties" rows={data.faculties} fields={[{name:'code',label:'Kod'},{name:'name',label:'Nomi'},{name:'dean',label:'Dekan'},{name:'phone',label:'Telefon'},{name:'email',label:'Email'}]}/>} 
  {page==='departments'&&<CrudPage title="Kafedra" collectionName="departments" rows={data.departments} lookups={lookups} fields={[{name:'code',label:'Kod'},{name:'name',label:'Nomi'},{name:'facultyId',label:'Fakultet',options:opts(data.faculties)},{name:'head',label:'Mudiri'},{name:'buildingId',label:'Bino',options:opts(data.buildings)}]}/>} 
  {page==='groups'&&<CrudPage title="Guruh" collectionName="groups" rows={data.groups} lookups={lookups} fields={[{name:'name',label:'Guruh'},{name:'facultyId',label:'Fakultet',options:opts(data.faculties)},{name:'departmentId',label:'Kafedra',options:opts(data.departments)},{name:'direction',label:'Yo‘nalish'},{name:'course',label:'Kurs'},{name:'studentCount',label:'Talaba soni',type:'number'}]}/>} 
  {page==='teachers'&&<CrudPage title="O‘qituvchi" collectionName="teachers" rows={data.teachers} lookups={lookups} fields={[{name:'name',label:'F.I.O.'},{name:'departmentId',label:'Kafedra',options:opts(data.departments)},{name:'rank',label:'Lavozim'},{name:'degree',label:'Daraja'},{name:'maxHours',label:'Max haftalik soat',type:'number'},{name:'phone',label:'Telefon'}]}/>} 
  {page==='subjects'&&<CrudPage title="Fan" collectionName="subjects" rows={data.subjects} lookups={lookups} fields={[{name:'code',label:'Kod'},{name:'name',label:'Fan nomi'},{name:'departmentId',label:'Kafedra',options:opts(data.departments)},{name:'credit',label:'Kredit',type:'number'},{name:'lectureHours',label:'Ma’ruza',type:'number'},{name:'practiceHours',label:'Amaliy',type:'number'},{name:'labHours',label:'Lab',type:'number'}]}/>} 
  {page==='rooms'&&<CrudPage title="Xona" collectionName="rooms" rows={data.rooms} lookups={lookups} fields={[{name:'number',label:'Xona'},{name:'buildingId',label:'Bino',options:opts(data.buildings)},{name:'type',label:'Turi'},{name:'capacity',label:'Sig‘im',type:'number'},{name:'equipment',label:'Jihoz'}]}/>} 
  {page==='analytics'&&<Analytics data={data} conflicts={conflicts} score={score}/>} 
 </Layout>
}
function Dashboard({data,conflicts,score}){return <div className="space-y-6"><div className="grid grid-cols-1 gap-4 md:grid-cols-5"><StatCard label="Guruhlar" value={data.groups.length} sub="Firestore" icon={Users} tone="blue"/><StatCard label="O‘qituvchilar" value={data.teachers.length} sub="ro‘yxatda" icon={GraduationCap} tone="violet"/><StatCard label="Fanlar" value={data.subjects.length} sub="o‘quv reja" icon={BookOpen} tone="emerald"/><StatCard label="Darslar" value={data.lessons.length} sub="haftalik" icon={CalendarCheck} tone="amber"/><StatCard label="Konflikt" value={conflicts.length} sub={`score ${score.score}%`} icon={AlertTriangle} tone="rose"/></div><SchedulePreview data={data}/></div>}
function Schedule({data,lookups}){async function submit(e){e.preventDefault(); const f=new FormData(e.currentTarget); await createItem('lessons',{groupId:f.get('groupId'),subjectId:f.get('subjectId'),teacherId:f.get('teacherId'),roomId:f.get('roomId'),day:Number(f.get('day')),pair:Number(f.get('pair')),type:f.get('type'),hours:Number(f.get('hours')||2)}); e.currentTarget.reset();}
 return <div className="space-y-5"><form onSubmit={submit} className="rounded-2xl border bg-white p-5 shadow-soft"><h2 className="mb-4 font-extrabold">Dars qo‘shish</h2><div className="grid gap-3 md:grid-cols-4">{[['groupId','Guruh',opts(data.groups)],['subjectId','Fan',opts(data.subjects)],['teacherId','O‘qituvchi',opts(data.teachers)],['roomId','Xona',opts(data.rooms,'number')]].map(([name,label,os])=><select key={name} name={name} className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm"><option value="">{label}</option>{os.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>)}<select name="day" className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm">{DAYS.map((d,i)=><option value={i} key={d}>{d}</option>)}</select><select name="pair" className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm">{PAIRS.map((p,i)=><option value={i} key={p}>{i+1}-juft {p}</option>)}</select><select name="type" className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm"><option value="lecture">Ma’ruza</option><option value="practice">Amaliy</option><option value="lab">Laboratoriya</option><option value="seminar">Seminar</option></select><input name="hours" type="number" defaultValue="2" className="rounded-xl border bg-slate-50 px-3 py-2.5 text-sm"/></div><button className="mt-4 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white">Saqlash</button></form><SchedulePreview data={data}/></div>}
function SchedulePreview({data}){return <div className="overflow-hidden rounded-2xl border bg-white shadow-soft"><div className="border-b px-5 py-4 font-extrabold">Haftalik jadval</div><div className="overflow-auto"><table className="min-w-[980px] w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3 text-left">Juft</th>{DAYS.map(d=><th className="p-3 text-left" key={d}>{d}</th>)}</tr></thead><tbody>{PAIRS.map((p,pi)=><tr key={p} className="border-t"><td className="p-3 font-bold text-slate-500">{pi+1}<br/><span className="text-xs font-normal">{p}</span></td>{DAYS.map((_,di)=><td className="p-2 align-top" key={di}>{data.lessons.filter(l=>Number(l.day)===di&&Number(l.pair)===pi).map(l=><div key={l.id} className={`mb-2 rounded-xl border-l-4 p-3 text-xs ${lessonTypeStyle[l.type]||lessonTypeStyle.lecture}`}><div className="font-extrabold">{findBy(data.subjects,l.subjectId)?.name||'Fan'}</div><div>{findBy(data.teachers,l.teacherId)?.name||'O‘qituvchi'}</div><div className="text-slate-500">{findBy(data.groups,l.groupId)?.name} • {findBy(data.rooms,l.roomId)?.number}</div></div>)}</td>)}</tr>)}</tbody></table></div></div>}
function Workloads({data}){return <div className="rounded-2xl border bg-white shadow-soft"><div className="border-b px-5 py-4"><h2 className="font-extrabold">O‘qituvchi yuklamalari</h2><p className="text-sm text-slate-500">Darslar soni va soatlar bo‘yicha avtomatik hisoblanadi.</p></div><table className="min-w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4 text-left">O‘qituvchi</th><th className="p-4">Yuklama</th><th className="p-4">Max</th><th className="p-4">Holat</th></tr></thead><tbody>{data.teachers.map(t=>{const h=teacherHours(t.id,data.lessons),m=Number(t.maxHours||18),pct=Math.round(h/m*100);return <tr key={t.id} className="border-t"><td className="p-4 font-bold">{t.name}</td><td className="p-4"><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${pct>100?'bg-rose-500':pct>80?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${Math.min(pct,100)}%`}}/></div><span className="text-xs text-slate-500">{h} soat • {pct}%</span></td><td className="p-4 text-center">{m}</td><td className="p-4 text-center font-bold">{pct>100?'Oshgan':pct>80?'Yuqori':'Normal'}</td></tr>})}</tbody></table></div>}
function Conflicts({conflicts,data}){return <div className="space-y-3">{conflicts.length===0?<div className="rounded-2xl border bg-white p-8 text-center font-bold text-emerald-700">Konflikt yo‘q</div>:conflicts.map((c,i)=><div key={i} className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><div className="font-extrabold text-rose-700">{c.message}</div><div className="mt-1 text-sm text-rose-600">{DAYS[c.a.day]}, {PAIRS[c.a.pair]}</div></div>)}</div>}
function Analytics({data,conflicts,score}){return <div className="space-y-5"><div className="grid md:grid-cols-4 gap-4"><StatCard label="Optimallik" value={score.score+'%'} icon={BrainCircuit} tone="emerald"/><StatCard label="Konflikt" value={conflicts.length} icon={AlertTriangle} tone="rose"/><StatCard label="Xonalar" value={data.rooms.length} icon={DoorOpen} tone="blue"/><StatCard label="Darslar" value={data.lessons.length} icon={CalendarCheck} tone="amber"/></div><Workloads data={data}/></div>}
